version: '3.7'
name: "clickhouse-compose"

services:
  clickhouse:
    networks:
      - global
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"   # HTTP-интерфейс
      - "9000:9032"   # Native TCP
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin
      CLICKHOUSE_DB: default



networks:
  global:
    external: true

volumes:
  clickhouse_data: